### ISSUE TITLE
Event tracking?

### ISSUE THREAD

**Issue by lougreenwood** [mike-north/ember-intercom-io#147]
Hello, does this add-on support event tracking?

I get the impression from the Intercom docs (https://docs.intercom.com/the-intercom-platform/track-events-in-intercom) that something like the following should send an event to Intercom:

```
        this.intercom.set('trackEvent', 'test-event', {
          event_meta: 'hello',
        });
```

But I seen nothing in the Intercom UI...

**Comment by Pingu69** [comment]
For me it works like this `get(this, 'intercom.api')('trackEvent', 'test-event');`, but it only does it for me in the application.js, no route or anything like that
