### ISSUE TITLE
Tracking events

### ISSUE THREAD

**Issue by Pingu69** [mike-north/ember-intercom-io#155]
I am trying to make the event tracking work. 

I am doing it like this right now: 

`get(this, 'intercom.api')('trackEvent', 'created-spot');`

My idea was to get the intercom from the api property of the addon.

And it works like that, but only in my `application.js` (I know because you can see it in the network). 

If I put the line `get(this, 'intercom.api')('trackEvent', 'created-spot');` in an action and toggle it with a button click, it doesn't work. I get no network or log at all. 

Any ideas?

**Comment by Pingu69** [comment]
Check out my PR to fix this https://github.com/mike-north/ember-intercom-io/pull/156

**Comment by donaldwasserman** [comment]
This was fixed previously, just cleaning things up.
