### ISSUE TITLE
[QUESTION]: What is userHashProp?

### ISSUE THREAD

**Issue by dmuneras** [mike-north/ember-intercom-io#258]
Hi @mike-north,

This is just a question. I haven't been able to find what is `userHashProp` in Intercom. The default value is `hash`, but looking at the Intercom docs I only can find an attribute called: `user_hash` (https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#section-data-attributes). 

When a look at the request send to Intercom, that value seems to be ignored. Is it a mistake or I am missing something?

Best regards,
Daniel.

**Comment by donaldwasserman** [comment]
Hi @dmuneras This is for enabling `secure_mode` in intercom.

**Comment by donaldwasserman** [comment]
@dmuneras  Here's the link from intercom.
