### ISSUE TITLE
Messenger launcher not displaying after updating Intercom App ID

### ISSUE THREAD

**Issue by xtagon** [mike-north/ember-intercom-io#345]
Hi,

We recently switched app IDs with Intercom (account merge) and updated our apps, but the one app that is using ember-intercom-io stopped showing the launcher. We're using the latest version of ember-intercom-io.

There's a setting in Intercom to always show the launcher for users and visitors, which we have enabled. The intercom client itself has an option hideDefaultLauncher which defaults to false. Our other apps had an issue where we had to set hideDefaultLauncher to false explicitly, and we think it's because Intercom changed the default.

In ember-intercom-io, however, you can't set it to false. It looks like it doesn't really default to false, it defaults to just not overriding it. See here:

https://github.com/mike-north/ember-intercom-io/blob/918175beee0ba8fb570a00943eae7bd92f2227c0/addon/services/intercom.js#L383-L385

I forked this library and Yarn add'd it in development mode to try and fix that, but unfortunately the Intercom launcher still doesn't display.

Is there anything I might be missing or didn't think of? I also reached out to Intercom, we'll see if they respond.

Thanks in advance!

**Comment by donaldwasserman** [comment]
Hey @xtagon - I don't think the `hideDefaultLauncher` attribute is the issue. 

This isn't actually supported by intercom, so I'm sort of just guessing here. Is this an issue for new users too? or just previous ones? Intercom stuffs a bunch of configuration into local storage (including data about the launcher) under the key `intercom-state`

Here's what the config for my app looks like:

<img width="1601" alt="Screen Shot 2020-08-13 at 5 19 56 AM" src="https://user-images.githubusercontent.com/5202922/90117313-bd237480-dd24-11ea-928c-51da142816b5.png">

**Comment by xtagon** [comment]
@donaldwasserman Thanks so much! This was the push in the right direction that we needed - Looks like the intercom-state storage was out of sync, and it eventually trued up overnight.

Cheers for helping me even though this library was not at fault! ❤
