### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by dbinetti** [mike-north/ember-intercom-io#58]
I've followed the default installation instructions carefully and the component is not loading.  Further, it doesn't show any errors in the console (or anywhere else I can see).

That said, if I set the `deferReadinessUntilLoaded` to `true` then I receive this error:

`ember.debug.js:19157 TypeError: Cannot read property 'then' of undefined
    at Object.initialize (ember-intercom.js:23)`

Any pointers on debugging?

thanks

**Comment by oxodesign** [comment]
Im having same issue? I think there is a pull request regarding this, hope @mike-north can merge it soon!

**Comment by seawatts** [comment]
Yes #36 should fix this.

**Comment by oxodesign** [comment]
@seawatts then hope @mike-north can merge it to master and do a new release soon!

**Comment by seawatts** [comment]
Closing, should be fixed in the next release.
